export const grey = '#5c626b'
// export const blue = '#2f95dc'
export const lightGrey = '#ccc'
export const white = '#fff'
export const blue = '#04afea'
export const green = '#04e5d4'
export const blueGreen = '#04ccde'
